COMPONENT=TestTimerAppC

CFLAGS += -DENABLE_PR

CFLAGS += -I../../tos/include
CFLAGS += -I../../tos/chips/msp430/timer
CFLAGS += -I../../tos/lib/timer
CFLAGS += -I../../tos/system
CFLAGS += -I$(TOSROOT)/tos/lib/printf

include $(MAKERULES)
