COMPONENT=TestSpiAppC

CFLAGS += -I../../tos/printf
CFLAGS += -I../../tos/chips/msp430/timer
CFLAGS += -I../../tos/chips/cc2420/x-spi
CFLAGS += -I../../tos/chips/cc2420/x-control
CFLAGS += -I../../tos/chips/cc2420/x-timer
CFLAGS += -I../../tos/chips/cc2420/x-rtx
CFLAGS += -I../../tos/chips/cc2420

include $(MAKERULES)
