COMPONENT=TestSpiAppC

CFLAGS += -I../../tos/printf
CFLAGS += -I../../tos/chips/msp430/timer
CFLAGS += -I../../tos/chips/cc2420/x-spi
CFLAGS += -I../../tos/chips/cc2420/x-control
CFLAGS += -I../../tos/chips/cc2420/x-timer
CFLAGS += -I../../tos/chips/cc2420/x-rtx
CFLAGS += -I../../tos/chips/cc2420
CFLAGS += -I../../tos/chips/cc2420/control
CFLAGS += -I../../tos/chips/cc2420/alarm
CFLAGS += -I../../tos/chips/cc2420/spi
CFLAGS += -I../../tos/chips/cc2420/control
CFLAGS += -I../../tos/chips/msp430/usart
CFLAGS += -I../../tos/chips/msp430/pins

include $(MAKERULES)
