COMPONENT=TestPrintfAppC

CFLAGS += -I../../tos/chips/msp430
CFLAGS += -I../../tos/chips/msp430/timer
CFLAGS += -I../../tos/chips/cc2420/x-spi
CFLAGS += -I../../tos/chips/cc2420/x-control
CFLAGS += -I../../tos/chips/cc2420/x-timer
CFLAGS += -I../../tos/chips/cc2420/x-rtx
CFLAGS += -I../../tos/chips/cc2420/x-packet
CFLAGS += -I../../tos/chips/cc2420/x-lpl
CFLAGS += -I../../tos/chips/cc2420/interfaces
CFLAGS += -I../../tos/chips/cc2420

CFLAGS += -I../../tos/platforms/telosa
CFLAGS += -I../../tos/lib/timer
CFLAGS += -I../../tos/system
CFLAGS += -I../../tos/printf

include $(MAKERULES)
